In [29]:
import numpy as np 

arr = np.random.randint(0,100,size=10)

print(arr)
print(arr.dtype)

[97 64 80 56 71 95  9  3 65 61]
int32


In [32]:
mat  = np.random.rand(5,5)

print(np.min(mat))
print(np.max(mat))

0.004888093670410876
0.9138732625971822


In [34]:
arr = np.random.rand(10)

arr_int = (arr * 10).astype(int)
print(arr)
print(arr_int)

[0.67462246 0.28305343 0.6307112  0.51224785 0.4807066  0.34419224
 0.41653709 0.43101972 0.95096474 0.74716764]
[6 2 6 5 4 3 4 4 9 7]


In [35]:
mat = np.random.randint(0,10,(3,3))
mat[1, :] = -1

print(mat)

[[ 4  3  9]
 [-1 -1 -1]
 [ 8  4  5]]


In [ ]:
data = {"fruta":["Banana","Maça","Pera"],                 
        "preco":[7,90,10,20,11,80],
        "quantidade":[12,3,4]
      }